"""Generate Cube Core data models (YAML) from the approved semantic context.

One cube per table: every column becomes a dimension, a `count` measure plus sum / avg for numeric
non-key columns, joins from the approved relationships. Descriptions come from the metadata layer, so
Cube's /meta endpoint and every Cube consumer see the same approved meaning.
"""
import re

import yaml


NUMERIC = re.compile(r"(int|numeric|decimal|float|double|real|number|money)", re.I)
TIME = re.compile(r"(date|time)", re.I)
BOOL = re.compile(r"bool", re.I)


def cube_name(table: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", table.lower()).strip("_")


def _dim_type(sql_type: str) -> str:
    if BOOL.search(sql_type):
        return "boolean"
    if TIME.search(sql_type):
        return "time"
    if NUMERIC.search(sql_type):
        return "number"
    return "string"


def _quote(ident: str) -> str:
    return '"' + ident.replace('"', '""') + '"'


def build_cubes(connection_name: str, metadata_layer: dict) -> list[dict]:
    tables = metadata_layer.get("tables", {})
    rels = metadata_layer.get("relationships", [])
    cubes = []
    for tname, t in tables.items():
        dims, measures = [], [{"name": "count", "type": "count", "description": f"Number of {tname} rows."}]
        pk = set(t.get("primary_key") or [])
        for cname, c in t["columns"].items():
            dtype = _dim_type(c.get("type", ""))
            dim = {"name": cube_name(cname), "sql": _quote(cname), "type": dtype,
                   "description": c.get("description") or cname}
            if cname in pk:
                dim["primary_key"] = True
                dim["public"] = True
            dims.append(dim)
            if dtype == "number" and cname not in pk and not cname.lower().endswith("_id"):
                for agg in ("sum", "avg"):
                    measures.append({"name": f"{agg}_{cube_name(cname)}", "sql": _quote(cname), "type": agg,
                                     "description": f"{agg.upper()} of {c.get('description') or cname}"})
        joins = []
        for r in rels:
            src_table, src_col = r["from"].rsplit(".", 1)
            dst_table, dst_col = r["to"].rsplit(".", 1)
            if src_table == tname and dst_table in tables and "," not in src_col:
                joins.append({"name": cube_name(dst_table), "relationship": r.get("type", "many_to_one"),
                              "sql": f"{{CUBE}}.{_quote(src_col)} = {{{cube_name(dst_table)}}}.{_quote(dst_col)}"})
        schema, _, name = tname.rpartition(".")
        cube = {"name": cube_name(tname), "sql_table": f"{_quote(schema)}.{_quote(name)}" if schema else _quote(name),
                "data_source": connection_name, "description": t.get("description") or tname,
                "dimensions": dims, "measures": measures}
        if joins:
            cube["joins"] = joins
        cubes.append(cube)
    return cubes


def cube_yaml(connection_name: str, version: int, metadata_layer: dict) -> str:
    header = f"# Generated by DataFusion from approved semantic context version {version}. Do not edit by hand.\n"
    return header + yaml.safe_dump({"cubes": build_cubes(connection_name, metadata_layer)}, sort_keys=False,
                                   allow_unicode=True)


def publish(db, connection_name: str, version: int, metadata_layer: dict) -> dict:
    """Store the generated model; Cube picks it up through the internal API on its next schema check."""
    from ..db import CubeModel
    row = db.get(CubeModel, connection_name) or CubeModel(connection_name=connection_name)
    row.context_version, row.yaml = version, cube_yaml(connection_name, version, metadata_layer)
    db.add(row)
    db.commit()
    return {"connection": connection_name, "context_version": version,
            "cubes": len(metadata_layer.get("tables", {}))}


def schema_version(db) -> str:
    from sqlalchemy import select
    from ..db import CubeModel
    rows = db.execute(select(CubeModel.connection_name, CubeModel.context_version)
                      .order_by(CubeModel.connection_name)).all()
    return ";".join(f"{n}:{v}" for n, v in rows) or "empty"
